
$CPAN::Config = {
  'auto_commit' => q[0],
  'build_cache' => q[100],
  'build_dir' => q[/Users/robb/.cpan/build],
  'cache_metadata' => q[1],
  'commandnumber_in_prompt' => q[1],
  'connect_to_internet_ok' => q[1],
  'cpan_home' => q[/Users/robb/.cpan],
  'ftp_passive' => q[1],
  'ftp_proxy' => q[],
  'http_proxy' => q[],
  'inactivity_timeout' => q[0],
  'index_expire' => q[1],
  'inhibit_startup_message' => q[0],
  'keep_source_where' => q[/Users/robb/.cpan/sources],
  'load_module_verbosity' => undef,
  'make_arg' => q[-j3],
  'make_install_arg' => q[UNINST=1],
  'make_install_make_command' => q[],
  'makepl_arg' => q[],
  'mbuild_arg' => q[],
  'mbuild_install_arg' => q[],
  'mbuild_install_build_command' => q[./Build],
  'mbuildpl_arg' => q[],
  'no_proxy' => q[],
  'prerequisites_policy' => q[ask],
  'scan_cache' => q[atstart],
  'show_upload_date' => q[0],
  'term_ornaments' => q[1],
  'urllist' => [q[ftp://ftp.wayne.edu/cpan/], q[ftp://mirror.atlantic.net/pub/CPAN/], q[ftp://mirror.candidhosting.com/pub/CPAN], q[ftp://mirror.cc.columbia.edu/pub/software/cpan/], q[ftp://mirror.cogentco.com/pub/CPAN/], q[ftp://mirror.datapipe.net/pub/CPAN/], q[ftp://mirror.hiwaay.net/CPAN/], q[ftp://mirror.its.uidaho.edu/cpan/], q[ftp://mirror.nyi.net/CPAN/]],
  'use_sqlite' => q[0],
};
1;
__END__
